### ISSUE TITLE
Can't make MoonGL in Windows using Mingw32-make

### ISSUE THREAD

**Issue by IWasAllen** [stetre/moongl#10]
I tried to follow the installation setup for windows according [here](https://github.com/stetre/moonlibs#installing-on-windows), using the mingw32-make that I downloaded from msys2.
But running the make commands keeps showing this error:
```
mingw32-make: Nothing to be done for 'C:\Users\user\Desktop\moonfltk'.
```

I used this command:
```
mingw32-make C:\Users\user\Desktop\moonfltk
```

Anybody could help?

**Comment by stetre** [comment]
The example in the instructions compiles moonfltk, not moongl. The process for moongl (and for the other libraries in the collection) is the same, but you must replace moonfltk with moongl. That is:

```
$ git clone https://github.com/stetre/moongl
$ cd moongl
moongl$ make
moongl$ sudo make install
```

**Comment by IWasAllen** [comment]
Thanks for the reply and correction for my installation.

However, running the `mingw32-make` command inside the moongl's directory throws an error:

```
The filename, directory name, or volume label syntax is incorrect.
Makefile:5: recipe for target 'build' failed
mingw32-make: *** [build] Error 1
```

**Comment by stetre** [comment]
Are you executing the command from a mingw shell, as per the instructions?

**Comment by IWasAllen** [comment]
I was executing it from command prompt, so this time I tried it to execute using make.exe from the msys
`C:\MinGW\msys\1.0\bin\make`

However it returns this error:
![image](https://user-images.githubusercontent.com/91869534/182018821-d51fa599-2c07-4464-b758-bee28b98d3e5.png)

**Comment by IWasAllen** [comment]
Oh wait, I'm stupid.
I didn't know there was a shell for mingw32.

So I tried executting the command inside the moongl directory using the moongl shell:
and this is the output:
```
$ make
make[1]: Entering directory `/c/Users/user/Desktop/moongl/src'
cc -O2 -Wall -Wextra -Wpedantic -DCOMPAT53_PREFIX=moongl_compat_ -std=gnu99 -DLUAVER=5.4 -fpic -DLINUX -I/usr/include -I/usr/include/lua5.4 -I/usr/local/include/lua5.4   -c -o bitfield.o bitfield.c
make[1]: cc: Command not found
make[1]: *** [bitfield.o] Error 127
make[1]: Leaving directory `/c/Users/user/Desktop/moongl/src'
make: *** [build] Error 2
```

**Comment by stetre** [comment]
Seems like you are missing the C compiler. To install it, again from the mingw shell, run this command:

```
$ pacman -S ${MINGW_PACKAGE_PREFIX}-gcc
```

**Comment by IWasAllen** [comment]
Unfortunately, I couldn't install CC due to msys.org is down right now, therefore I can't download the pacman package.

But there was a workaround since I already have gcc installed, assuming that it's a C compiler. I added this line at the beginning of the MakeFile: `CC=gcc`.

Now it gave me this output when I run the make command:
```
make[1]: Entering directory `/c/Users/user/Desktop/moongl/src'
gcc -O2 -Wall -Wextra -Wpedantic -DCOMPAT53_PREFIX=moongl_compat_ -std=gnu99 -DLUAVER=5.4 -fpic -DLINUX -I/usr/include -I/usr/include/lua5.4 -I/usr/local/include/lua5.4   -c -o bitfield.o bitfield.c
In file included from internal.h:35:0,
                 from bitfield.c:26:
moongl.h:33:17: fatal error: lua.h: No such file or directory
 #include <lua.h>
                 ^
compilation terminated.
make[1]: *** [bitfield.o] Error 1
make[1]: Leaving directory `/c/Users/user/Desktop/moongl/src'
make: *** [build] Error 2
```

I already have the lua.h files of Lua 5.4, where would I put it so that it can recognize?

**Comment by stetre** [comment]
You should install the whole Lua 5.4 package. You need not only the headers but the libraries also.
Better if you install it via pacman (msys2.org seems up to me), otherwise you can install it manually.
Download the tar.gz from [lua.org](https://www.lua.org/download.html), then this should do:

```
$ tar -zxvf lua-5.4.4.tar.gz
$ cd lua-5.4.4
$ make mingw
$ make mingw install
```

**Comment by IWasAllen** [comment]
Thanks, I finally have downloaded msys2 from mysys2.org and I already installed the make, lua and other commands using pacman.
Now using the `make` command inside the moongl, it throws another error about missing file:
```
$ make
make[1]: Entering directory '/home/Allen/moongl/src'
cc -O2 -Wall -Wextra -Wpedantic -DCOMPAT53_PREFIX=moongl_compat_ -std=gnu99 -DLUAVER=5.4 -DMINGW    -c -o bitfield.o bitfield.c
In file included from internal.h:35,
                 from bitfield.c:26:
moongl.h:38:10: fatal error: GL/glew.h: No such file or directory
   38 | #include <GL/glew.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: bitfield.o] Error 1
make[1]: Leaving directory '/home/Allen/moongl/src'
make: *** [Makefile:5: build] Error 2
```

**Comment by stetre** [comment]
You can find plenty of working examples in moongl/examples and subfolders, which you can execute as you would with pure-lua scripts. Among them, there are ports of almost all the examples from learnopengl.com and from the book OpenGL 4 Shading Language Cookbook.

You'll need other libraries to run them, though, because OpenGL (and thus MoonGL) by itself deals only with graphics rendering and not with other aspects needed by a graphic application, such as surface/window creation, input handling, perhaps audio rendering, and so on.

See the readme in each moongl/examples subfolder for the list of required additional libraries. The installation process is the same for all of them (don't forget the dependencies...).

**Comment by IWasAllen** [comment]
No way, I actually manage to render a window in moongl. I'm also getting the hang of it when installing some moongl dependencies.

Thank you so much for helping me throughout this installation!
