### ISSUE TITLE
Mingw make command?

### ISSUE THREAD

**Issue by Yaumama** [stetre/moongl#8]
Hello, I have installed mingw64 and added the bin to path, however make is not there. I see mingw32-make and I tried using that, but I got an error. Can anyone help?

**Comment by stetre** [comment]
It's hard to help if you don't say which error you get.

However, it should work out of the box if you use MSYS2 and follow the [instructions](https://github.com/stetre/moonlibs#installing-on-windows).

**Comment by Yaumama** [comment]
I followed the instructions and managed to find a make command. I still get the error though. Here it is:
```make[1]: Entering directory '/d/CodeProjects/MoonGL/moongl/src'
cc -O2 -Wall -Wextra -Wpedantic -DCOMPAT53_PREFIX=moongl_compat_ -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I/usr/include -I/usr/include/lua5.3 -I/usr/local/include/lua5.3   -c -o bitfield.o bitfield.c
make[1]: cc: No such file or directory
make[1]: *** [<builtin>: bitfield.o] Error 127
make[1]: Leaving directory '/d/CodeProjects/MoonGL/moongl/src'
make: *** [Makefile:5: build] Error 2```

**Comment by stetre** [comment]
Seems like you have not installed gcc, or you have not set the Windows PATH variable correctly.

**Comment by stetre** [comment]
Did the pacman commands succeed? If so, then you should have the complete toolchain installed including make and gcc, and they should be executable from the mingw shell. You can check that this is the case by running `$ which make` and `$ which gcc`.

**Comment by Yaumama** [comment]
It seems they did! Here is a screenshot.
![image](https://user-images.githubusercontent.com/83031256/149565380-cbc4b4a9-8cf1-4420-ac05-671f9b85b523.png)

**Comment by stetre** [comment]
Then it should work...

Try cloning a fresh copy of moongl, and compile from there (as per the instructions):

```
$ git clone https://github.com/stetre/moonfltk
$ cd moonfltk
moonfltk$ make
```

**Comment by Yaumama** [comment]
Hello sorry for late response, it is still not working. Perhaps due to me not mentioning that I am on windows. I am sorry for not mentioning it before. I don't know what to do if this doesn't fix it.

**Comment by stetre** [comment]
Don't worry, I assumed you were on Windows since you are using mingw.

Do you still get the same error you posted earlier? Try also `$ which cc`.

**Comment by Yaumama** [comment]
Yes I am still getting the same error. And with the `$ which cc` command this is the output I get:
![image](https://user-images.githubusercontent.com/83031256/149667592-f1136cbe-1e2a-47b2-b021-9e6008531acc.png)

**Comment by stetre** [comment]
Seems like make doesn't find cc, which by the way should be in /usr/bin/cc . This is strange, however, since the which command can find it.

If it's not a problem, I would recommend you to reinstall MSYS2 and repeat the instructions step-by-step. Maybe the current install didn't go well, for some reason. Before doing that, however, you could try creating a soft link to cc in /usr/bin, to see if this fixes the problem.

**Comment by Yaumama** [comment]
Hello, I do not know what a soft link is on windows, and could not find anything. Can you specify it?

**Comment by stetre** [comment]
From the mingw shell, just do this:

```
$ cd /usr/bin
$ ln -s /mingw64/bin/cc cc
```

This should create a file named cc in /usr/bin, that is just a link to /mingw64/bin/cc . The effect is as if you copied cc in /usr/bin .

I'm not sure that soft links are supported in MSYS2, though, so it may not work. As an alternative, you can edit the Makefile in moongl/src and add the following line at the top:

`
CC = /mingw64/bin/cc
`

**Comment by Yaumama** [comment]
I did that and got this error instead:

```make[1]: Entering directory '/d/CodeProjects/MoonGL/moongl/src'
cc -O2 -Wall -Wextra -Wpedantic -DCOMPAT53_PREFIX=moongl_compat_ -std=gnu99 -DLUAVER=5.3 -fpic -DLINUX -I/usr/include -I/usr/include/lua5.3 -I/usr/local/include/lua5.3   -c -o bitfield.o bitfield.c
D:/msys64/usr/bin/cc: error while loading shared libraries: libwinpthread-1.dll: cannot open shared object file: No such file or directory
make[1]: *** [<builtin>: bitfield.o] Error 127
make[1]: Leaving directory '/d/CodeProjects/MoonGL/moongl/src'
make: *** [Makefile:6: build] Error 2

**Comment by stetre** [comment]
There seems to be some problem with the MSYS2 install (missing stuff, mainly). As a I suggested earlier, maybe it's worth reinstalling it from zero. Follow closely the instructions at https://www.msys2.org/ , and be sure not to skip the post installation steps (steps 5 to 7). Then repeat those at https://github.com/stetre/moonlibs#installing-on-windows to install MoonGL.

(TBH, it's been a while since I last did this, but as far as I can remember things used to go fairly smooth every time I tried, and it seems unlikely to me that MSYS2 changed drastically in the meanwhile. )

**Comment by Yaumama** [comment]
Ok, I will try this. Do I just uninstall with the windows setting?

**Comment by stetre** [comment]
Yes, that should do. Then reinstall everything, carefully following the described steps.

**Comment by Yaumama** [comment]
I did everything, however I still get the same error. I really want to set this up because it sounds like a really cool thing. So I am going to keep trying. If you have any idea, please help. I even got a new fresh copy of moongl.
